### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/the_fork_awakens#141]
**Description:**
Update Readme with newest documentation

- **Features:** Add newest image and screenshots of the features
- **Am I Responsive** Update Image
- **Bugs** Update bugs section if there is any bugs, if not write no bugs

**Tasks:**

- [x] Add newest images to the features
- [x] Update Am I Responsive image
- [x] Update bugs section
- [x] Update table of contents if needed
