### ISSUE TITLE
Update Testing

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/the_fork_awakens#142]
**Description:**
Update Testing with newest documentation

- **HTML validation** 
- **CSS validation**
- **Lighthouse** 
- **JavaScript validation**
- **Manual Testing** 
-Do as many manual tests you can and write the in down in the table
-Such as testing the link button, testing return home button, testing mute button, testing responsiveness etc.

**Tasks:**

- [x] Validate all HTML files and screenshot results and attach them to testing.md
- [x] Validate all CSS files and screenshot results and attach them to testing.md
- [x] Check console logs for Javascript errors, if aall good write down a paragraph that it works as expected
- [x] Fill the table with manual testing checks

**Comment by Thomas-Tomo** [comment]
Validate html and css and javascript with a few paragraphs that explain it, we don't need screenshots
