### ISSUE TITLE
Consistent design check

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/the_fork_awakens#144]
**Description:**
Go through the website and make sure the design is consistent and responsive on all screens

- **Test the design** 
- **Look for any possible changes that might add for a better design**

**Tasks:**

- [x] Review the implemented design to make sure it suits the website 
- [x] Fix any minor issues
- [x] Test the responsivenes
