### ISSUE TITLE
Create a presentation and record it

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/the_fork_awakens#145]
**Description:**
Screen record the latest version of the project and create a presentation 

- **Record a presentation** 
- **Ensure it is 3 minutes long, not more**
- **Must be submitted before 15pm Monday**

**Tasks:**

- [x] Record a reative presentation
- [x] Ensure the video is not longer than 3 minutes
- [x] Verify the format that needs to be submitted to the judges
- [x] Once recorded, submit the presenation, Repo URL and Live project URL to the judges, check the form in hackathon slack channel
