### ISSUE TITLE
Review the modal design and functionality

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/the_fork_awakens#146]
**Description:**
Review the modal design, functionality needs to be checked for the win, image is not showing when user wins

- **Review the modal design** 
- **Test the modal**

**Tasks:**

- [x] Review the modal design
- [x] Test the modal functionality
- [x] Test responsiveness on all screens
- [x] Make sure image shows up in modal after quiz is won
